name: CI

# Build and test the Bunt application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Xcode
      run: |
        xcodebuild -project Bunt.xcodeproj -configuration Release build